name: GitHub Readme Stats
on:
  schedule:
    - cron: "0 0 * * *" # Atualiza uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Gerar Card de Estatisticas
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dracula&include_all_commits=true
          path: stats.svg # Salva o arquivo na raiz
          token: ${{ secrets.PAT_1 }}

      - name: Commit e Push das Estatísticas
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@github.com"
          git add stats.svg
          git commit -m "docs: atualiza estatísticas do perfil [skip ci]" || echo "Sem alterações para salvar"
          git push
